[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "mevzuat-mcp-server"
source = "mevzuat-mcp"

[services.variables]
PORT = "8080"
HOST = "0.0.0.0"
PYTHON_VERSION = "3.13" 